/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 19 13:10:14 GMT 2019
 */

package myRobot;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Graphics2D;
import java.awt.geom.Point2D;
import java.awt.image.BufferedImage;
import myRobot.WaveSurfing;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import robocode.AdvancedRobot;
import robocode.Bullet;
import robocode.HitByBulletEvent;
import robocode.ScannedRobotEvent;
import sun.java2d.SunGraphics2D;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WaveSurfing_ESTest extends WaveSurfing_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double();
      double double0 = WaveSurfing.absoluteBearing(point2D_Double0, point2D_Double0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      WaveSurfing waveSurfing0 = new WaveSurfing(advancedRobot0);
      Point2D.Double point2D_Double0 = new Point2D.Double(160.0, (-1435.7129238939));
      waveSurfing0._enemyLocation = point2D_Double0;
      // Undeclared exception!
      try { 
        waveSurfing0.predictPosition((WaveSurfing.EnemyWave) null, 47);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("myRobot.WaveSurfing", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double();
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      WaveSurfing waveSurfing0 = new WaveSurfing(advancedRobot0);
      // Undeclared exception!
      try { 
        waveSurfing0.logHit((WaveSurfing.EnemyWave) null, point2D_Double0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("myRobot.WaveSurfing", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      WaveSurfing waveSurfing0 = new WaveSurfing(advancedRobot0);
      Point2D.Double point2D_Double0 = new Point2D.Double(100.0, 100.0);
      double double0 = waveSurfing0.wallSmoothing(point2D_Double0, 0.0, 0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      WaveSurfing waveSurfing0 = new WaveSurfing(advancedRobot0);
      Point2D.Double point2D_Double0 = new Point2D.Double();
      double double0 = waveSurfing0.wallSmoothing(point2D_Double0, (-1062.969577988), 2);
      assertEquals((-1061.6695779880013), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      double double0 = WaveSurfing.maxEscapeAngle(2317.1979011137455);
      assertEquals(0.003452452588856905, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      double double0 = WaveSurfing.limit(0.0, 360.0, (-1796.738));
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      double double0 = WaveSurfing.limit((-515.968166), 0.5, (-3786.885643042));
      assertEquals((-515.968166), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      double double0 = WaveSurfing.bulletVelocity((-1.0));
      assertEquals(23.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      WaveSurfing waveSurfing0 = new WaveSurfing(advancedRobot0);
      Point2D.Double point2D_Double0 = new Point2D.Double((-277.713414663), (-277.713414663));
      // Undeclared exception!
      waveSurfing0.wallSmoothing(point2D_Double0, 0.0, (-836));
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      // Undeclared exception!
      try { 
        WaveSurfing.setBackAsFront(advancedRobot0, 0.0);
        fail("Expecting exception: Error");
      
      } catch(Error e) {
         //
         // You cannot call the getHeadingRadians() method before your run() method is called, or you are using a Robot object that the game doesn't know about.
         //
         verifyException("robocode._RobotBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      // Undeclared exception!
      try { 
        WaveSurfing.setBackAsFront((AdvancedRobot) null, 47);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("myRobot.WaveSurfing", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      // Undeclared exception!
      try { 
        WaveSurfing.project((Point2D.Double) null, 100.0, 764.0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      WaveSurfing waveSurfing0 = new WaveSurfing(advancedRobot0);
      WaveSurfing.EnemyWave waveSurfing_EnemyWave0 = waveSurfing0.new EnemyWave();
      // Undeclared exception!
      try { 
        waveSurfing0.predictPosition(waveSurfing_EnemyWave0, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("myRobot.WaveSurfing", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      WaveSurfing waveSurfing0 = new WaveSurfing(advancedRobot0);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent("", (-884.0498), (-1987.8497996926), 3571.0, 0.0, (-870.235889056));
      // Undeclared exception!
      try { 
        waveSurfing0.onScannedRobot(scannedRobotEvent0);
        fail("Expecting exception: Error");
      
      } catch(Error e) {
         //
         // You cannot call the getX() method before your run() method is called, or you are using a Robot object that the game doesn't know about.
         //
         verifyException("robocode._RobotBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      WaveSurfing waveSurfing0 = new WaveSurfing((AdvancedRobot) null);
      ScannedRobotEvent scannedRobotEvent0 = new ScannedRobotEvent("", 100.0, 418.26998228553, 418.26998228553, 36.0, 418.26998228553, true);
      // Undeclared exception!
      try { 
        waveSurfing0.onScannedRobot(scannedRobotEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("myRobot.WaveSurfing", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      WaveSurfing waveSurfing0 = new WaveSurfing(advancedRobot0);
      // Undeclared exception!
      try { 
        waveSurfing0.onPaint((Graphics2D) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("myRobot.WaveSurfing", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      // Undeclared exception!
      try { 
        WaveSurfing.absoluteBearing((Point2D.Double) null, (Point2D.Double) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("myRobot.WaveSurfing", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      WaveSurfing waveSurfing0 = new WaveSurfing(advancedRobot0);
      WaveSurfing.EnemyWave waveSurfing_EnemyWave0 = waveSurfing0.getClosestSurfableWave();
      assertNull(waveSurfing_EnemyWave0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double(3459.636825214108, 1916.3032993214);
      Point2D.Double point2D_Double1 = WaveSurfing.project(point2D_Double0, 0.0, 3459.636825214108);
      double double0 = WaveSurfing.absoluteBearing(point2D_Double1, point2D_Double0);
      assertEquals(3.141592653589793, double0, 0.01);
      assertEquals(5375.9401245355075, point2D_Double1.y, 0.01);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      WaveSurfing waveSurfing0 = new WaveSurfing(advancedRobot0);
      BufferedImage bufferedImage0 = new BufferedImage(47, 47, 1);
      SunGraphics2D sunGraphics2D0 = (SunGraphics2D)bufferedImage0.createGraphics();
      waveSurfing0.onPaint(sunGraphics2D0);
      assertEquals(0, sunGraphics2D0.clipState);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      WaveSurfing waveSurfing0 = new WaveSurfing(advancedRobot0);
      Point2D.Double point2D_Double0 = new Point2D.Double();
      double double0 = waveSurfing0.wallSmoothing(point2D_Double0, 0.0, 664);
      assertEquals(132.8, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      WaveSurfing waveSurfing0 = new WaveSurfing(advancedRobot0);
      HitByBulletEvent hitByBulletEvent0 = new HitByBulletEvent(0.0, (Bullet) null);
      waveSurfing0.onHitByBullet(hitByBulletEvent0);
      assertEquals(0.0, hitByBulletEvent0.getBearingRadians(), 0.01);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      WaveSurfing waveSurfing0 = new WaveSurfing(advancedRobot0);
      waveSurfing0.doSurfing();
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      WaveSurfing waveSurfing0 = new WaveSurfing(advancedRobot0);
      waveSurfing0.updateWaves();
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      double double0 = WaveSurfing.limit(0.0, 7.050000000000001, 160.0);
      assertEquals(7.050000000000001, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double(941.5876032, (-6232.371798));
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      WaveSurfing waveSurfing0 = new WaveSurfing(advancedRobot0);
      WaveSurfing.EnemyWave waveSurfing_EnemyWave0 = waveSurfing0.new EnemyWave();
      // Undeclared exception!
      try { 
        WaveSurfing.getFactorIndex(waveSurfing_EnemyWave0, point2D_Double0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("myRobot.WaveSurfing", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      double double0 = WaveSurfing.bulletVelocity(801.637);
      assertEquals((-2384.911), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      double double0 = WaveSurfing.maxEscapeAngle((byte) (-57));
      assertEquals((-0.14081579077234008), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      WaveSurfing waveSurfing0 = new WaveSurfing(advancedRobot0);
      // Undeclared exception!
      try { 
        waveSurfing0.wallSmoothing((Point2D.Double) null, 0.0, 747);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      WaveSurfing waveSurfing0 = new WaveSurfing(advancedRobot0);
      WaveSurfing.EnemyWave waveSurfing_EnemyWave0 = waveSurfing0.new EnemyWave();
      // Undeclared exception!
      try { 
        waveSurfing0.checkDanger(waveSurfing_EnemyWave0, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("myRobot.WaveSurfing", e);
      }
  }
}
